from flask import Flask, render_template, request, redirect, url_for, session
from leitor import buscar_codigo  # sua função que lê o código do e-mail

app = Flask(__name__)
app.secret_key = 'chave_super_secreta_123'

TRANSLATIONS = {
    'pt': {
        'store_name': 'Henrique Store',
        'title': 'Buscar código Netflix',
        'placeholder': 'Digite o e-mail da conta Netflix',
        'button': 'Buscar',
        'result': 'Código encontrado:',
        'not_found': 'Nenhum código encontrado para',
        'language_label': '🌐 Idioma:',
        'footer_text': '© 2025 Henrique Store – Todos os direitos reservados.',
        'instagram': 'Instagram',
        'ggmax': 'Nossa Loja',
        'whatsapp': 'WhatsApp',
        'help_text': 'Se precisar de ajuda ou tenha alguma dúvida, contate pelo WhatsApp:',
        'click_here': 'Clique aqui',
        'searching': 'Buscando código...',
        'faq_title': 'FAQ – Perguntas Frequentes',
        'faq_q1': 'Como solicitar o código único de login?',
        'faq_a1': 'Acesse a página ou app oficial da Netflix (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › Clique em \'Usar um código de acesso\' › Digite seu e-mail da conta › Clique em \'Enviar código de acesso\' › Copie o código em nosso site › Clique em \'Entrar\' › Escolha seu perfil e use seu PIN.',
        'faq_q2': 'Está dando senha incorreta, o que fazer?',
        'faq_a2': 'Se estiver no navegador ou mobile, limpe os dados e cache do aplicativo, ou reinstale por completo.',
        'faq_q3': 'Fiz todos o processo de limpeza de dados e continua dando senha incorreta',
        'faq_a3': 'Use uma VPN para países comuns: Brasil, Estados Unidos, França e Espanha.',
        'faq_q4': 'Fiz todos os processos e continua com senha incorreta',
        'faq_a4': 'Clique no botão de ajuda logo abaixo e aguarde a resposta da equipe.',
        'faq_q5': 'Posso renovar o plano no mesmo perfil?',
        'faq_a5': 'Sim, basta falar com a gente no WhatsApp e iremos lhe explicar todo o procedimento.',
        'faq_q6': 'Minha conta caiu, o que devo fazer?',
        'faq_a6': 'Acione o suporte logo abaixo e explique o problema.',
        'whatsapp_icon': '💬 Suporte'
    },
    'en': {
        'store_name': 'Henrique Store',
        'title': 'Find Netflix Code',
        'placeholder': 'Enter the Netflix account email',
        'button': 'Search',
        'result': 'Code found:',
        'not_found': 'No code found for',
        'language_label': '🌐 Language:',
        'footer_text': '© 2025 Henrique Store – All rights reserved.',
        'instagram': 'Instagram',
        'ggmax': 'Our Store',
        'whatsapp': 'WhatsApp',
        'help_text': 'If you need help or have questions, contact us on WhatsApp:',
        'click_here': 'Click here',
        'searching': 'Searching code...',
        'faq_title': 'FAQ – Frequently Asked Questions',
        'faq_q1': 'How do I request the unique login code?',
        'faq_a1': 'Go to the official Netflix website or app (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › Click "Use access code" › Enter your account email › Click "Send access code" › Copy the code here › Click "Sign in" › Select your profile and enter your PIN.',
        'faq_q2': 'It says incorrect password, what do I do?',
        'faq_a2': 'If on browser or mobile, clear app data and cache, or reinstall completely.',
        'faq_q3': 'I cleared data and it still says incorrect password',
        'faq_a3': 'Use a VPN with common countries: Brazil, United States, France, Spain.',
        'faq_q4': 'I did everything and it still says incorrect password',
        'faq_a4': 'Click the help button below and wait for support.',
        'faq_q5': 'Can I renew the plan using the same profile?',
        'faq_a5': 'Yes, just contact us on WhatsApp and we’ll guide you.',
        'faq_q6': 'My account is no longer working, what should I do?',
        'faq_a6': 'Contact support below and describe the issue.',
        'whatsapp_icon': '💬 Support'
    },
    'es': {
        'store_name': 'Henrique Store',
        'title': 'Buscar código de Netflix',
        'placeholder': 'Ingresa el correo de la cuenta de Netflix',
        'button': 'Buscar',
        'result': 'Código encontrado:',
        'not_found': 'No se encontró ningún código para',
        'language_label': '🌐 Idioma:',
        'footer_text': '© 2025 Henrique Store – Todos los derechos reservados.',
        'instagram': 'Instagram',
        'ggmax': 'Nuestra tienda',
        'whatsapp': 'WhatsApp',
        'help_text': 'Si necesitas ayuda o tienes dudas, contáctanos por WhatsApp:',
        'click_here': 'Haz clic aquí',
        'searching': 'Buscando código...',
        'faq_title': 'FAQ – Preguntas Frecuentes',
        'faq_q1': '¿Cómo solicitar el código único de acceso?',
        'faq_a1': 'Ve al sitio o app oficial de Netflix (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › Haz clic en "Usar un código de acceso" › Ingresa tu correo electrónico › Haz clic en "Enviar código de acceso" › Copia el código aquí › Haz clic en "Iniciar sesión" › Elige tu perfil y escribe tu PIN.',
        'faq_q2': 'Me dice que la contraseña es incorrecta, ¿qué hago?',
        'faq_a2': 'Si estás en navegador o móvil, borra datos y caché o reinstala la app.',
        'faq_q3': 'Limpié datos y sigue diciendo contraseña incorrecta',
        'faq_a3': 'Usa una VPN con países comunes: Brasil, Estados Unidos, Francia y España.',
        'faq_q4': 'Hice todo y aún dice contraseña incorrecta',
        'faq_a4': 'Haz clic en el botón de ayuda y espera la respuesta del equipo.',
        'faq_q5': '¿Puedo renovar el plan en el mismo perfil?',
        'faq_a5': 'Sí, contáctanos por WhatsApp y te explicaremos cómo.',
        'faq_q6': 'Mi cuenta ya no funciona, ¿qué hago?',
        'faq_a6': 'Habla con soporte abajo y cuéntanos tu problema.',
        'whatsapp_icon': '💬 Soporte'
    },
    'fr': {
        'store_name': 'Henrique Store',
        'title': 'Rechercher un code Netflix',
        'placeholder': 'Entrez l’e-mail du compte Netflix',
        'button': 'Rechercher',
        'result': 'Code trouvé :',
        'not_found': 'Aucun code trouvé pour',
        'language_label': '🌐 Langue :',
        'footer_text': '© 2025 Henrique Store – Tous droits réservés.',
        'instagram': 'Instagram',
        'ggmax': 'Notre magasin',
        'whatsapp': 'WhatsApp',
        'help_text': 'Besoin d’aide ? Contactez-nous sur WhatsApp :',
        'click_here': 'Cliquez ici',
        'searching': 'Recherche du code...',
        'faq_title': 'FAQ – Questions Fréquemment Posées',
        'faq_q1': 'Comment demander le code de connexion unique ?',
        'faq_a1': 'Rendez-vous sur le site ou l’app Netflix (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › Cliquez sur "Utiliser un code d’accès" › Entrez votre e-mail › Cliquez sur "Envoyer le code" › Copiez le code ici › Cliquez sur "Se connecter" › Choisissez votre profil et entrez votre code PIN.',
        'faq_q2': 'Mot de passe incorrect, que faire ?',
        'faq_a2': 'Effacez les données et le cache de l’application, ou réinstallez-la.',
        'faq_q3': 'J’ai effacé les données mais cela indique toujours un mot de passe incorrect',
        'faq_a3': 'Utilisez un VPN vers le Brésil, les États-Unis, la France ou l’Espagne.',
        'faq_q4': 'Rien ne fonctionne, toujours mot de passe incorrect',
        'faq_a4': 'Cliquez sur le bouton d’aide ci-dessous et attendez une réponse.',
        'faq_q5': 'Puis-je renouveler l’abonnement avec le même profil ?',
        'faq_a5': 'Oui, contactez-nous sur WhatsApp pour les instructions.',
        'faq_q6': 'Mon compte ne fonctionne plus, que faire ?',
        'faq_a6': 'Contactez l’assistance via le bouton ci-dessous.',
        'whatsapp_icon': '💬 Assistance'
    },
    'de': {
        'store_name': 'Henrique Store',
        'title': 'Netflix-Code suchen',
        'placeholder': 'Netflix-Konto-E-Mail eingeben',
        'button': 'Suchen',
        'result': 'Code gefunden:',
        'not_found': 'Kein Code gefunden für',
        'language_label': '🌐 Sprache:',
        'footer_text': '© 2025 Henrique Store – Alle Rechte vorbehalten.',
        'instagram': 'Instagram',
        'ggmax': 'Unser Shop',
        'whatsapp': 'WhatsApp',
        'help_text': 'Bei Fragen kontaktieren Sie uns bitte über WhatsApp:',
        'click_here': 'Hier klicken',
        'searching': 'Code wird gesucht...',
        'faq_title': 'FAQ – Häufig gestellte Fragen',
        'faq_q1': 'Wie fordere ich den Einmal-Login-Code an?',
        'faq_a1': 'Besuche die Netflix-Website oder App (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › Klicke auf „Zugangscode verwenden“ › Gib deine E-Mail ein › Klicke auf „Code senden“ › Kopiere ihn hier › Klicke auf „Einloggen“ › Wähle dein Profil und gib deine PIN ein.',
        'faq_q2': 'Falsches Passwort – was tun?',
        'faq_a2': 'Lösche App-Daten und Cache oder installiere die App neu.',
        'faq_q3': 'Ich habe alles gelöscht, trotzdem falsches Passwort',
        'faq_a3': 'Nutze ein VPN in Brasilien, USA, Frankreich oder Spanien.',
        'faq_q4': 'Alles probiert, funktioniert trotzdem nicht',
        'faq_a4': 'Klicke auf den Hilfe-Button unten und warte auf eine Antwort.',
        'faq_q5': 'Kann ich mit dem gleichen Profil verlängern?',
        'faq_a5': 'Ja, schreibe uns auf WhatsApp und wir helfen dir weiter.',
        'faq_q6': 'Mein Konto ist weg – was tun?',
        'faq_a6': 'Kontaktiere den Support über den Button unten.',
        'whatsapp_icon': '💬 Support'
    },
    'zh': {
        'store_name': 'Henrique 商店',
        'title': '查找 Netflix 验证码',
        'placeholder': '请输入 Netflix 账户的电子邮件',
        'button': '搜索',
        'result': '找到的验证码：',
        'not_found': '未找到与以下内容相关的验证码：',
        'language_label': '🌐 语言：',
        'footer_text': '© 2025 Henrique 商店 – 保留所有权利。',
        'instagram': 'Instagram',
        'ggmax': '我们的商店',
        'whatsapp': 'WhatsApp',
        'help_text': '如需帮助或有任何疑问，请通过 WhatsApp 联系我们：',
        'click_here': '点击这里',
        'searching': '正在查找验证码...',
        'faq_title': '常见问题 – FAQ',
        'faq_q1': '如何申请唯一的登录验证码？',
        'faq_a1': '访问 Netflix 官方网站或应用程序（<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>）› 点击“使用访问代码”› 输入您的账户电子邮件 › 点击“发送访问代码”› 在我们的网站粘贴代码 › 点击“登录” › 选择您的资料并输入 PIN。',
        'faq_q2': '显示密码错误怎么办？',
        'faq_a2': '请清除应用程序的数据和缓存，或完全重新安装。',
        'faq_q3': '清除后仍然显示密码错误怎么办？',
        'faq_a3': '请使用 VPN，推荐国家：巴西、美国、法国、西班牙。',
        'faq_q4': '尝试所有方法后仍显示错误密码怎么办？',
        'faq_a4': '点击下方帮助按钮，等待支持团队回复。',
        'faq_q5': '我可以在同一个资料上续订套餐吗？',
        'faq_a5': '可以，请通过 WhatsApp 联系我们获取说明。',
        'faq_q6': '我的账户失效了，我该怎么办？',
        'faq_a6': '请通过下方按钮联系支持并说明问题。',
        'whatsapp_icon': '💬 支持'
    },

    'jp': {
        'store_name': 'Henrique ストア',
        'title': 'Netflixコードを検索',
        'placeholder': 'Netflixアカウントのメールアドレスを入力',
        'button': '検索',
        'result': '見つかったコード：',
        'not_found': '次のアカウントに対してコードが見つかりません：',
        'language_label': '🌐 言語：',
        'footer_text': '© 2025 Henrique ストア – 全著作権所有。',
        'instagram': 'Instagram',
        'ggmax': '当店',
        'whatsapp': 'WhatsApp',
        'help_text': 'ご不明な点がございましたら、WhatsApp でお問い合わせください：',
        'click_here': 'こちらをクリック',
        'searching': 'コードを検索中...',
        'faq_title': 'FAQ – よくある質問',
        'faq_q1': 'ログイン用のコードをリクエストするには？',
        'faq_a1': 'Netflixの公式サイトまたはアプリ（<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>）にアクセス › 「アクセスコードを使用」をクリック › メールアドレスを入力 › 「コードを送信」› 当サイトに貼り付け › 「ログイン」 › プロフィールを選択し、PINを入力します。',
        'faq_q2': 'パスワードが間違っていると表示されたら？',
        'faq_a2': 'ブラウザまたはモバイルの場合、アプリのデータとキャッシュを削除するか、再インストールしてください。',
        'faq_q3': 'データを削除してもエラーが続く場合は？',
        'faq_a3': 'VPNを使用してください。おすすめの国：ブラジル、アメリカ、フランス、スペイン。',
        'faq_q4': 'すべて試してもログインできない場合は？',
        'faq_a4': '下のヘルプボタンをクリックして、サポートをお待ちください。',
        'faq_q5': '同じプロフィールでプランを更新できますか？',
        'faq_a5': 'はい、WhatsApp でお問い合わせください。手順をご案内します。',
        'faq_q6': 'アカウントが使えなくなった場合は？',
        'faq_a6': '下のサポートボタンからお問い合わせください。',
        'whatsapp_icon': '💬 サポート'
    },

    'ko': {
        'store_name': 'Henrique 스토어',
        'title': 'Netflix 코드 찾기',
        'placeholder': 'Netflix 계정 이메일을 입력하세요',
        'button': '검색',
        'result': '찾은 코드:',
        'not_found': '다음에 대한 코드를 찾을 수 없습니다:',
        'language_label': '🌐 언어:',
        'footer_text': '© 2025 Henrique 스토어 – 모든 권리 보유.',
        'instagram': 'Instagram',
        'ggmax': '우리 가게',
        'whatsapp': 'WhatsApp',
        'help_text': '도움이 필요하거나 궁금한 점이 있으시면 WhatsApp으로 문의하세요:',
        'click_here': '여기를 클릭하세요',
        'searching': '코드 검색 중...',
        'faq_title': 'FAQ – 자주 묻는 질문',
        'faq_q1': '고유 로그인 코드를 요청하려면?',
        'faq_a1': 'Netflix 공식 웹사이트 또는 앱 (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) 에 접속 › "접속 코드 사용" 클릭 › 이메일 입력 › "코드 전송" 클릭 › 사이트에 붙여넣기 › "로그인" 클릭 › 프로필 선택 후 PIN 입력.',
        'faq_q2': '비밀번호 오류가 나타날 때는?',
        'faq_a2': '브라우저나 모바일에서 앱 데이터를 삭제하거나 재설치해 보세요.',
        'faq_q3': '데이터를 삭제해도 오류가 지속될 경우?',
        'faq_a3': 'VPN을 사용해 보세요. 추천 국가: 브라질, 미국, 프랑스, 스페인.',
        'faq_q4': '모든 방법을 시도했지만 여전히 로그인 안 될 때는?',
        'faq_a4': '아래의 도움말 버튼을 클릭하고 지원을 기다려 주세요.',
        'faq_q5': '같은 프로필로 요금제를 갱신할 수 있나요?',
        'faq_a5': '네, WhatsApp으로 문의해 주세요. 절차를 안내해 드립니다.',
        'faq_q6': '계정이 정지되었어요. 어떻게 하나요?',
        'faq_a6': '아래 지원 버튼을 통해 문제를 설명해 주세요.',
        'whatsapp_icon': '💬 지원'
    },
    
    'ar': {
        'store_name': 'متجر Henrique',
        'title': 'البحث عن رمز Netflix',
        'placeholder': 'أدخل البريد الإلكتروني لحساب Netflix',
        'button': 'بحث',
        'result': 'تم العثور على الرمز:',
        'not_found': 'لم يتم العثور على رمز لـ',
        'language_label': '🌐 اللغة:',
        'footer_text': '© 2025 متجر Henrique – جميع الحقوق محفوظة.',
        'instagram': 'إنستغرام',
        'ggmax': 'متجرنا',
        'whatsapp': 'واتساب',
        'help_text': 'إذا كنت بحاجة إلى مساعدة أو لديك أي استفسارات، تواصل معنا عبر واتساب:',
        'click_here': 'اضغط هنا',
        'searching': 'جارٍ البحث عن الرمز...',
        'faq_title': 'الأسئلة الشائعة – FAQ',
        'faq_q1': 'كيف يمكنني طلب رمز تسجيل الدخول الفريد؟',
        'faq_a1': 'اذهب إلى موقع أو تطبيق Netflix الرسمي (<a href="https://www.netflix.com/" target="_blank">https://www.netflix.com/</a>) › اضغط على "استخدام رمز وصول" › أدخل بريدك الإلكتروني › اضغط "إرسال رمز" › انسخ الرمز إلى موقعنا › اضغط "تسجيل الدخول" › اختر ملفك الشخصي وأدخل الرقم السري.',
        'faq_q2': 'ظهرت رسالة "كلمة المرور غير صحيحة"، ماذا أفعل؟',
        'faq_a2': 'إذا كنت تستخدم المتصفح أو الجوال، امسح بيانات التطبيق وذاكرة التخزين المؤقت، أو قم بإعادة التثبيت.',
        'faq_q3': 'قمت بمسح البيانات وما زالت تظهر كلمة مرور خاطئة',
        'faq_a3': 'استخدم VPN لدول مثل: البرازيل، الولايات المتحدة، فرنسا، إسبانيا.',
        'faq_q4': 'جربت كل شيء وما زالت تظهر كلمة مرور غير صحيحة',
        'faq_a4': 'اضغط على زر المساعدة أدناه وانتظر رد الفريق.',
        'faq_q5': 'هل يمكنني تجديد الخطة بنفس الملف الشخصي؟',
        'faq_a5': 'نعم، فقط تواصل معنا عبر واتساب وسنشرح لك الطريقة.',
        'faq_q6': 'تم تعليق حسابي، ماذا أفعل؟',
        'faq_a6': 'تواصل مع الدعم عبر الزر أدناه واشرح المشكلة.',
        'whatsapp_icon': '💬 دعم'
    }


    # Se quiser, posso complementar com zh, jp, ko.
}

@app.route('/', methods=['GET', 'POST'])
def index():
    email = ''
    codigo = None
    lang = session.get('lang', 'pt')
    t = TRANSLATIONS.get(lang, TRANSLATIONS['pt'])

    if request.method == 'POST':
        email = request.form.get('email')
        codigo = buscar_codigo(email)

    return render_template("index.html", t=t, email=email, codigo=codigo, lang=lang)

@app.route('/set_lang/<lang>')
def set_language(lang):
    if lang in TRANSLATIONS:
        session['lang'] = lang
    return redirect(url_for('index'))

if __name__ == '__main__':
    app.run(debug=True)
